import java.sql.*;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import java.util.TimerTask;  
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kiara
 */
public class EasyFl1Paladin extends javax.swing.JFrame implements TOMInterface{

        int m,i=0, n;
        Timer timer, ntime, Optimer,rtimer;
        String narrate;
        int mark = 0, mak = 0;
        private DecimalFormat df = new DecimalFormat("0");
        //Player Stats
        private int playerHP;
        private int armor;
        private String bossName;
        private String bossSkill;
        private int experiencePoints = 0;
        private int experienceThreshold = 30; 
        private int playerLevel = 1;
        private int levelDamageMultiplier = 1;
        //Mob/Enemy Stats
        private int monsterHP1 = 50; //goblin
        private int monsterHP2 = 70; //undead
        private double monsterArmor1;
        private double monsterArmor2;
        private int monsterDamage1;
        private int monsterDamage2;
        private int monsterCount = 0;
        //Boss
        private int bossHP;
        private double bossArmor;
        private int bossDamage;
        private int bossCounterAttackDamage;
        private int bossCount = 0;
        //Floor 
        private int currentFloor = 1;
        private double floorHPMultiplier = 0.2;
        private int floorDamage = 0;
        //Skill
        private int skillDamage;
        private int skillCooldown = 3;
        private int turnsSinceLastSkill = skillCooldown;
        boolean defeatedMonster1 = false;
        boolean defeatedMonster2 = false;
        private Random random = new Random();
        private Clip clip;
        private int attackCount;
        private double points;
    /**
     * Creates new form StartGame
     */
    public EasyFl1Paladin() {
        initComponents();
        jLayeredPane1.setVisible(false);
        JpaneChamIdle.setVisible(false);
        JpaneAttack.setVisible(false);
        JpaneAttack2.setVisible(false);
        JpaneStrike.setVisible(false);
        JLayeredDeadPaladin.setVisible(false);
        jPaneEmAttack.setVisible(false);
        JpaneDef.setVisible(false);
        jPaneEmDead1.setVisible(false);
        jPaneEmDead2.setVisible(false);
        jPaneEmDead22.setVisible(false);
        jPaneEmDead222.setVisible(false);
        jpaneSave.setVisible(false);
        YouWin.setVisible(false);
        this.setBackground(Color.decode("#3D748F"));
        initIntro();
    }
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpaneBack = new javax.swing.JLayeredPane();
        YouWin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPaneCover = new javax.swing.JLayeredPane();
        lblCover = new javax.swing.JLabel();
        JpaneGoblin = new javax.swing.JLayeredPane();
        lblGoblin = new javax.swing.JLabel();
        JpaneAttack = new javax.swing.JLayeredPane();
        lblAttack = new javax.swing.JLabel();
        JpaneAttack2 = new javax.swing.JLayeredPane();
        lblAttack2 = new javax.swing.JLabel();
        JpaneBoosIdle = new javax.swing.JLayeredPane();
        lblBoss = new javax.swing.JLabel();
        JpaneChamStart = new javax.swing.JLayeredPane();
        ldlChamStart = new javax.swing.JLabel();
        JpaneDef = new javax.swing.JLayeredPane();
        lblDefend = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblRunning = new javax.swing.JLabel();
        JLayeredDeadPaladin = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        JpaneEmFalling = new javax.swing.JLayeredPane();
        lblEmFalling = new javax.swing.JLabel();
        jPaneEmAttack = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        JpaneChamIdle = new javax.swing.JLayeredPane();
        lblIdle = new javax.swing.JLabel();
        jPaneEmDead1 = new javax.swing.JLayeredPane();
        lblEmDead1 = new javax.swing.JLabel();
        jPaneEmDead2 = new javax.swing.JLayeredPane();
        lblEmDead2 = new javax.swing.JLabel();
        jPaneEmDead222 = new javax.swing.JLayeredPane();
        lblEmDead222 = new javax.swing.JLabel();
        jPaneEmDead22 = new javax.swing.JLayeredPane();
        lblEmDead22 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lblEmFalling2 = new javax.swing.JLabel();
        jPaneUndead = new javax.swing.JLayeredPane();
        lblUndead = new javax.swing.JLabel();
        JpaneStrike = new javax.swing.JLayeredPane();
        lblStrike = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDia = new javax.swing.JTextArea();
        jpaneSave = new javax.swing.JLayeredPane();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnSkill = new javax.swing.JButton();
        btnBasicAttack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(61, 116, 143));
        setForeground(new java.awt.Color(61, 116, 143));
        setMaximumSize(new java.awt.Dimension(960, 672));
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        JpaneBack.setMaximumSize(new java.awt.Dimension(960, 672));
        JpaneBack.setMinimumSize(new java.awt.Dimension(960, 672));

        YouWin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/YOU WIN.gif"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/fb2ab0e7-4d0a-4fea-b77c-34aa0f6a194b.gif"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/fb2ab0e7-4d0a-4fea-b77c-34aa0f6a194b.gif"))); // NOI18N
        lblCover.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPaneCover.setLayer(lblCover, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPaneCoverLayout = new javax.swing.GroupLayout(jPaneCover);
        jPaneCover.setLayout(jPaneCoverLayout);
        jPaneCoverLayout.setHorizontalGroup(
            jPaneCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 911, Short.MAX_VALUE)
        );
        jPaneCoverLayout.setVerticalGroup(
            jPaneCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCover, javax.swing.GroupLayout.PREFERRED_SIZE, 123, Short.MAX_VALUE)
        );

        JpaneGoblin.setForeground(new java.awt.Color(255, 255, 255));

        lblGoblin.setForeground(new java.awt.Color(255, 255, 255));
        lblGoblin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Goblins.gif"))); // NOI18N

        JpaneGoblin.setLayer(lblGoblin, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout JpaneGoblinLayout = new javax.swing.GroupLayout(JpaneGoblin);
        JpaneGoblin.setLayout(JpaneGoblinLayout);
        JpaneGoblinLayout.setHorizontalGroup(
            JpaneGoblinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneGoblinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGoblin, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpaneGoblinLayout.setVerticalGroup(
            JpaneGoblinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneGoblinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGoblin, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        lblAttack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Slash 2_1.gif"))); // NOI18N
        lblAttack.setToolTipText("");

        JpaneAttack.setLayer(lblAttack, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout JpaneAttackLayout = new javax.swing.GroupLayout(JpaneAttack);
        JpaneAttack.setLayout(JpaneAttackLayout);
        JpaneAttackLayout.setHorizontalGroup(
            JpaneAttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneAttackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpaneAttackLayout.setVerticalGroup(
            JpaneAttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneAttackLayout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(lblAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblAttack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Slash 3.gif"))); // NOI18N

        JpaneAttack2.setLayer(lblAttack2, javax.swing.JLayeredPane.MODAL_LAYER);

        javax.swing.GroupLayout JpaneAttack2Layout = new javax.swing.GroupLayout(JpaneAttack2);
        JpaneAttack2.setLayout(JpaneAttack2Layout);
        JpaneAttack2Layout.setHorizontalGroup(
            JpaneAttack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneAttack2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAttack2)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        JpaneAttack2Layout.setVerticalGroup(
            JpaneAttack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneAttack2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblAttack2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        lblBoss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/output-onlinegiftools (2).gif"))); // NOI18N

        JpaneBoosIdle.setLayer(lblBoss, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout JpaneBoosIdleLayout = new javax.swing.GroupLayout(JpaneBoosIdle);
        JpaneBoosIdle.setLayout(JpaneBoosIdleLayout);
        JpaneBoosIdleLayout.setHorizontalGroup(
            JpaneBoosIdleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneBoosIdleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBoss, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JpaneBoosIdleLayout.setVerticalGroup(
            JpaneBoosIdleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneBoosIdleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBoss, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ldlChamStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Paladin IDLE_1.gif"))); // NOI18N

        JpaneChamStart.setLayer(ldlChamStart, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout JpaneChamStartLayout = new javax.swing.GroupLayout(JpaneChamStart);
        JpaneChamStart.setLayout(JpaneChamStartLayout);
        JpaneChamStartLayout.setHorizontalGroup(
            JpaneChamStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneChamStartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ldlChamStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpaneChamStartLayout.setVerticalGroup(
            JpaneChamStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ldlChamStart)
        );

        lblDefend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/output-onlinegiftools (4) (1).gif"))); // NOI18N

        JpaneDef.setLayer(lblDefend, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout JpaneDefLayout = new javax.swing.GroupLayout(JpaneDef);
        JpaneDef.setLayout(JpaneDefLayout);
        JpaneDefLayout.setHorizontalGroup(
            JpaneDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneDefLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(lblDefend, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpaneDefLayout.setVerticalGroup(
            JpaneDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneDefLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDefend)
                .addGap(41, 41, 41))
        );

        lblRunning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Paladin RUN_1.gif"))); // NOI18N
        lblRunning.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblRunningPropertyChange(evt);
            }
        });

        jLayeredPane1.setLayer(lblRunning, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunning, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRunning, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/paladindead (1).gif"))); // NOI18N
        jLabel1.setText("jLabel1");

        JLayeredDeadPaladin.setLayer(jLabel1, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout JLayeredDeadPaladinLayout = new javax.swing.GroupLayout(JLayeredDeadPaladin);
        JLayeredDeadPaladin.setLayout(JLayeredDeadPaladinLayout);
        JLayeredDeadPaladinLayout.setHorizontalGroup(
            JLayeredDeadPaladinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JLayeredDeadPaladinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JLayeredDeadPaladinLayout.setVerticalGroup(
            JLayeredDeadPaladinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLayeredDeadPaladinLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        lblEmFalling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Goblins.gif"))); // NOI18N

        JpaneEmFalling.setLayer(lblEmFalling, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout JpaneEmFallingLayout = new javax.swing.GroupLayout(JpaneEmFalling);
        JpaneEmFalling.setLayout(JpaneEmFallingLayout);
        JpaneEmFallingLayout.setHorizontalGroup(
            JpaneEmFallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneEmFallingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmFalling, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JpaneEmFallingLayout.setVerticalGroup(
            JpaneEmFallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneEmFallingLayout.createSequentialGroup()
                .addComponent(lblEmFalling, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 210, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Slash 1.gif"))); // NOI18N

        jPaneEmAttack.setLayer(jLabel3, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout jPaneEmAttackLayout = new javax.swing.GroupLayout(jPaneEmAttack);
        jPaneEmAttack.setLayout(jPaneEmAttackLayout);
        jPaneEmAttackLayout.setHorizontalGroup(
            jPaneEmAttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneEmAttackLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPaneEmAttackLayout.setVerticalGroup(
            jPaneEmAttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneEmAttackLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        lblIdle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Paladin IDLE_1.gif"))); // NOI18N

        JpaneChamIdle.setLayer(lblIdle, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout JpaneChamIdleLayout = new javax.swing.GroupLayout(JpaneChamIdle);
        JpaneChamIdle.setLayout(JpaneChamIdleLayout);
        JpaneChamIdleLayout.setHorizontalGroup(
            JpaneChamIdleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIdle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JpaneChamIdleLayout.setVerticalGroup(
            JpaneChamIdleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneChamIdleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIdle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        lblEmDead1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/GoblinsDam_1.gif"))); // NOI18N

        jPaneEmDead1.setLayer(lblEmDead1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPaneEmDead1Layout = new javax.swing.GroupLayout(jPaneEmDead1);
        jPaneEmDead1.setLayout(jPaneEmDead1Layout);
        jPaneEmDead1Layout.setHorizontalGroup(
            jPaneEmDead1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneEmDead1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmDead1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPaneEmDead1Layout.setVerticalGroup(
            jPaneEmDead1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneEmDead1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmDead1)
                .addGap(34, 34, 34))
        );

        lblEmDead2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/GoblinsDamm_1.gif"))); // NOI18N

        jPaneEmDead2.setLayer(lblEmDead2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPaneEmDead2Layout = new javax.swing.GroupLayout(jPaneEmDead2);
        jPaneEmDead2.setLayout(jPaneEmDead2Layout);
        jPaneEmDead2Layout.setHorizontalGroup(
            jPaneEmDead2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneEmDead2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmDead2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPaneEmDead2Layout.setVerticalGroup(
            jPaneEmDead2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneEmDead2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmDead2)
                .addGap(37, 37, 37))
        );

        lblEmDead222.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Undead2.gif"))); // NOI18N

        jPaneEmDead222.setLayer(lblEmDead222, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPaneEmDead222Layout = new javax.swing.GroupLayout(jPaneEmDead222);
        jPaneEmDead222.setLayout(jPaneEmDead222Layout);
        jPaneEmDead222Layout.setHorizontalGroup(
            jPaneEmDead222Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneEmDead222Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblEmDead222, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPaneEmDead222Layout.setVerticalGroup(
            jPaneEmDead222Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneEmDead222Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmDead222)
                .addGap(38, 38, 38))
        );

        lblEmDead22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Undead22.gif"))); // NOI18N

        jPaneEmDead22.setLayer(lblEmDead22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPaneEmDead22Layout = new javax.swing.GroupLayout(jPaneEmDead22);
        jPaneEmDead22.setLayout(jPaneEmDead22Layout);
        jPaneEmDead22Layout.setHorizontalGroup(
            jPaneEmDead22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneEmDead22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmDead22, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPaneEmDead22Layout.setVerticalGroup(
            jPaneEmDead22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneEmDead22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmDead22)
                .addGap(41, 41, 41))
        );

        lblEmFalling2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Undead (1).gif"))); // NOI18N

        jLayeredPane2.setLayer(lblEmFalling2, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmFalling2)
                .addGap(27, 27, 27))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(lblEmFalling2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 232, Short.MAX_VALUE))
        );

        lblUndead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Undead (1).gif"))); // NOI18N

        jPaneUndead.setLayer(lblUndead, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout jPaneUndeadLayout = new javax.swing.GroupLayout(jPaneUndead);
        jPaneUndead.setLayout(jPaneUndeadLayout);
        jPaneUndeadLayout.setHorizontalGroup(
            jPaneUndeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneUndeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUndead)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPaneUndeadLayout.setVerticalGroup(
            jPaneUndeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneUndeadLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblUndead)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        lblStrike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Paladin attack.gif"))); // NOI18N

        JpaneStrike.setLayer(lblStrike, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout JpaneStrikeLayout = new javax.swing.GroupLayout(JpaneStrike);
        JpaneStrike.setLayout(JpaneStrikeLayout);
        JpaneStrikeLayout.setHorizontalGroup(
            JpaneStrikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneStrikeLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lblStrike, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JpaneStrikeLayout.setVerticalGroup(
            JpaneStrikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneStrikeLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(lblStrike, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JpaneBack.setLayer(YouWin, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JpaneBack.setLayer(jPaneCover, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(JpaneGoblin, javax.swing.JLayeredPane.PALETTE_LAYER);
        JpaneBack.setLayer(JpaneAttack, javax.swing.JLayeredPane.POPUP_LAYER);
        JpaneBack.setLayer(JpaneAttack2, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(JpaneBoosIdle, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(JpaneChamStart, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(JpaneDef, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(JLayeredDeadPaladin, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(JpaneEmFalling, javax.swing.JLayeredPane.POPUP_LAYER);
        JpaneBack.setLayer(jPaneEmAttack, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(JpaneChamIdle, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(jPaneEmDead1, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(jPaneEmDead2, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(jPaneEmDead222, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(jPaneEmDead22, javax.swing.JLayeredPane.DRAG_LAYER);
        JpaneBack.setLayer(jLayeredPane2, javax.swing.JLayeredPane.POPUP_LAYER);
        JpaneBack.setLayer(jPaneUndead, javax.swing.JLayeredPane.POPUP_LAYER);
        JpaneBack.setLayer(JpaneStrike, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout JpaneBackLayout = new javax.swing.GroupLayout(JpaneBack);
        JpaneBack.setLayout(JpaneBackLayout);
        JpaneBackLayout.setHorizontalGroup(
            JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(257, 257, 257)
                    .addComponent(JpaneChamIdle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(593, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(621, 621, 621)
                    .addComponent(JpaneBoosIdle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(558, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(339, 339, 339)
                    .addComponent(JpaneGoblin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(482, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(352, 352, 352)
                    .addComponent(JpaneAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(430, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(254, 254, 254)
                    .addComponent(JpaneStrike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(559, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(316, 316, 316)
                    .addComponent(JpaneAttack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(420, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JpaneChamStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(792, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(259, 259, 259)
                    .addComponent(JLayeredDeadPaladin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(575, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(250, 250, 250)
                    .addComponent(jPaneEmAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(430, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(342, 342, 342)
                    .addComponent(JpaneEmFalling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(428, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addComponent(jPaneCover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 22, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(JpaneDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(521, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(339, 339, 339)
                    .addComponent(jPaneEmDead1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(491, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(336, 336, 336)
                    .addComponent(jPaneEmDead2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(494, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(404, 404, 404)
                    .addComponent(jPaneUndead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(434, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(388, 388, 388)
                    .addComponent(jPaneEmDead222, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(452, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(411, 411, 411)
                    .addComponent(jPaneEmDead22, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(447, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(412, 412, 412)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(413, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(259, 259, 259)
                    .addComponent(YouWin, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(275, Short.MAX_VALUE)))
        );
        JpaneBackLayout.setVerticalGroup(
            JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneBackLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(JpaneChamIdle, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(318, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(JpaneBoosIdle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(216, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(224, 224, 224)
                    .addComponent(JpaneGoblin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(316, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(JpaneAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(330, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(JpaneStrike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(325, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(JpaneAttack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(309, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(230, 230, 230)
                    .addComponent(JpaneChamStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(193, 193, 193)
                    .addComponent(JLayeredDeadPaladin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jPaneEmAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(229, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JpaneEmFalling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(330, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addComponent(jPaneCover, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 550, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(JpaneDef, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(314, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(205, 205, 205)
                    .addComponent(jPaneEmDead1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(329, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addComponent(jPaneEmDead2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(328, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(168, 168, 168)
                    .addComponent(jPaneUndead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(281, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addComponent(jPaneEmDead222, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(327, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addComponent(jPaneEmDead22, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(333, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(318, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(YouWin)
                    .addContainerGap(173, Short.MAX_VALUE)))
        );

        txtDia.setBackground(new java.awt.Color(57, 114, 196));
        txtDia.setColumns(20);
        txtDia.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtDia.setLineWrap(true);
        txtDia.setRows(5);
        txtDia.setWrapStyleWord(true);
        txtDia.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(61, 116, 143)));
        txtDia.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDia.setMargin(new java.awt.Insets(0, 6, 2, 6));
        jScrollPane1.setViewportView(txtDia);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jpaneSave.setLayer(txtName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpaneSave.setLayer(btnSave, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpaneSaveLayout = new javax.swing.GroupLayout(jpaneSave);
        jpaneSave.setLayout(jpaneSaveLayout);
        jpaneSaveLayout.setHorizontalGroup(
            jpaneSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSave)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jpaneSaveLayout.setVerticalGroup(
            jpaneSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaneSaveLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jpaneSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addGap(35, 35, 35))
        );

        btnSkill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Air Swipe.gif"))); // NOI18N

        btnBasicAttack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Slash 2 (1).gif"))); // NOI18N
        btnBasicAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasicAttackActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jpaneSave, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane3.setLayer(btnSkill, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnBasicAttack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(756, Short.MAX_VALUE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSkill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBasicAttack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(213, 213, 213)
                    .addComponent(jpaneSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(213, Short.MAX_VALUE)))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(btnBasicAttack)
                .addGap(18, 18, 18)
                .addComponent(btnSkill)
                .addGap(40, 40, 40))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jpaneSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpaneBack, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(519, 519, 519))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpaneBack, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(646, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRunningPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblRunningPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRunningPropertyChange

    private void btnBasicAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasicAttackActionPerformed
    jLayeredPane1.setVisible(true);
    JpaneChamStart.setVisible(false);

    playerAttack();  // Perform player's attack immediately
    }//GEN-LAST:event_btnBasicAttackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       String Name = txtName.getText();
       
            String url = "jdbc:mysql://localhost:3306/leaderboard";
            String username = "root";
            String password = "";
            String insertQuery = "INSERT INTO leaderboard (name ,stage) VALUES (?,?)";
            String selectQuery = "SELECT stage FROM leaderboard";
            try {
            // Load and register the JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Establish a connection
            Connection connection = DriverManager.getConnection(url, username, password);
            
            // Create a PreparedStatement for insert
            PreparedStatement insertStatement = connection.prepareStatement(insertQuery);
            
            
            // Set the name parameter for insert
            insertStatement.setString(1,Name );
            insertStatement.setDouble(2, points);
            
            // Execute the insert query
            int rowsAffected = insertStatement.executeUpdate();
            
            // Close the insert statement
            insertStatement.close();
   
            connection.close();
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
        Introduction obj = new Introduction();
            obj.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void reset(){
        txtDia.setText("\n\t Enter Name for leaderboard:");
        
        jpaneSave.setVisible(true);
            
            
            
    }
    private void initPlayerAttack() {
    Timer attackTimer = new Timer(1000, new ActionListener() {
        private int count = 0;

        @Override
        public void actionPerformed(ActionEvent e) {
            switch (count) {
                case 0:
                    playerAttack();
                    if (areOpponentsAlive() == 0) {
                        ((Timer) e.getSource()).stop(); // Stop the timer if no opponents are alive
                    }
                    break;
                case 1:
                    opponentsAttack();
                    if (isPlayerAlive() == 0) {
                        System.out.println("\nGame Over!");
                        ((Timer) e.getSource()).stop(); // Stop the timer if player is dead
                    }
                    break;
                default:
                    ((Timer) e.getSource()).stop(); // Stop the timer after all actions are processed
                    break;
            }
            count++;
        }
    });
    attackTimer.setInitialDelay(0); // Start immediately
    attackTimer.start();
}

    
    private void initIntro(){
        i=0;
        playerHP = 10000;
            armor = random.nextInt(31)+30;
            monsterArmor1 = random.nextInt(14);
            monsterArmor2 = random.nextInt(7);
            monsterHP1 += monsterArmor1;
            monsterHP2 += monsterArmor2;
        playerHP +=armor;
         btnBasicAttack.setEnabled(false);
        
        String intro;
        intro = "Paladin's Armor Activated. Paladin gained " + armor + " Additional HP.\n"
                + getMonsterName1()+"'s Armor Activated. "+getMonsterName1()+" gained " + df.format(monsterArmor1) + " Additional HP.\n"
                + getMonsterName2()+"'s Armor Activated. "+getMonsterName2()+" gained " + df.format(monsterArmor2) + " Additional HP.\n"
                + " - - - You are on floor " + currentFloor+" - - - "
                +"\n\n" + getHeroType() + "'s HP: " + getPlayerHP() 
                +" |"+getMonsterName1()+ ": " + df.format(getMonsterHP1()) 
                +" |"+getMonsterName2()+ ": " + df.format(getMonsterHP2()) 
                +" | Floor: " + currentFloor;

            System.out.print("Pleas Select Attack: ");;
         timer = new Timer(5, new ActionListener(){
    @Override
        public void actionPerformed(ActionEvent e) {
        
             if (i < intro.length()) {
                    txtDia.append(String.valueOf(intro.charAt(i)));
                    i++;
                } else {
                    timer.stop();
                    btnBasicAttack.setEnabled(true);
                }
        }
        });
         
        timer.setDelay(20);
        timer.start();
              
    }
    
    private void Update(){
        i = 0;
        String up = "\n\n" + getHeroType() + "'s HP: " + getPlayerHP() 
                +" |"+getMonsterName1()+ ": " + df.format(getMonsterHP1()) 
                +" |"+getMonsterName2()+ ": " + df.format(getMonsterHP2()) 
                +" | Floor: " + currentFloor + points;
         ntime = new Timer(5, new ActionListener(){
    @Override
        public void actionPerformed(ActionEvent e) {
        
             if (i < up.length()) {
                    txtDia.append(String.valueOf(up.charAt(i)));
                    i++;
                } else {
                    ntime.stop();
                }
        }
        });
         
        ntime.setDelay(20);
        ntime.start();
              
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyFl1Paladin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyFl1Paladin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyFl1Paladin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyFl1Paladin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyFl1Paladin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane JLayeredDeadPaladin;
    private javax.swing.JLayeredPane JpaneAttack;
    private javax.swing.JLayeredPane JpaneAttack2;
    private javax.swing.JLayeredPane JpaneBack;
    private javax.swing.JLayeredPane JpaneBoosIdle;
    private javax.swing.JLayeredPane JpaneChamIdle;
    private javax.swing.JLayeredPane JpaneChamStart;
    private javax.swing.JLayeredPane JpaneDef;
    private javax.swing.JLayeredPane JpaneEmFalling;
    private javax.swing.JLayeredPane JpaneGoblin;
    private javax.swing.JLayeredPane JpaneStrike;
    private javax.swing.JLabel YouWin;
    private javax.swing.JButton btnBasicAttack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSkill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jPaneCover;
    private javax.swing.JLayeredPane jPaneEmAttack;
    private javax.swing.JLayeredPane jPaneEmDead1;
    private javax.swing.JLayeredPane jPaneEmDead2;
    private javax.swing.JLayeredPane jPaneEmDead22;
    private javax.swing.JLayeredPane jPaneEmDead222;
    private javax.swing.JLayeredPane jPaneUndead;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane jpaneSave;
    private javax.swing.JLabel lblAttack;
    private javax.swing.JLabel lblAttack2;
    private javax.swing.JLabel lblBoss;
    private javax.swing.JLabel lblCover;
    private javax.swing.JLabel lblDefend;
    private javax.swing.JLabel lblEmDead1;
    private javax.swing.JLabel lblEmDead2;
    private javax.swing.JLabel lblEmDead22;
    private javax.swing.JLabel lblEmDead222;
    private javax.swing.JLabel lblEmFalling;
    private javax.swing.JLabel lblEmFalling2;
    private javax.swing.JLabel lblGoblin;
    private javax.swing.JLabel lblIdle;
    private javax.swing.JLabel lblRunning;
    private javax.swing.JLabel lblStrike;
    private javax.swing.JLabel lblUndead;
    private javax.swing.JLabel ldlChamStart;
    private javax.swing.JTextArea txtDia;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
    public void levelUp() {
  
             experienceThreshold += 20;
            playerHP += 50;
            skillDamage += 15;
            levelDamageMultiplier += 4;           
            playerLevel++;

            txtDia.append(" \n- - - Congratulations! You leveled up to level " + playerLevel +
            ". Stats are increased! - - -\n ");

            // Reset experiencePoints
            experiencePoints = 0;

        }
    
    public void resetOpponents() {
            mark = 0;
            mak=0;
            monsterHP1 = 30;
            monsterHP2 = 50;

            monsterArmor1 = random.nextDouble(31) * floorHPMultiplier;
            monsterArmor2 = random.nextDouble(21) * floorHPMultiplier;

            System.out.println(getMonsterName1()+"'s Armor Activated. "+getMonsterName1()+" gained " + df.format(monsterArmor1) + " Additional HP.");
            System.out.println(getMonsterName2()+"'s Armor Activated. "+getMonsterName2()+" gained " +df.format(monsterArmor2) + " Additional HP.");

            monsterHP1 += monsterArmor1;
            monsterHP2 += monsterArmor2;
            m=5;
          
            JpaneGoblin.setVisible(false);
            jPaneUndead.setVisible(false);
            JpaneDef.setVisible(false);
            
             rtimer = new Timer(2, new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent e) {
        Point p = lblCover.getLocation();
        Point g = lblEmFalling.getLocation();
        Point u = lblEmFalling2.getLocation();
        m = m + 5;
        lblEmFalling2.setLocation(+5,+m);
        lblEmFalling.setLocation(+5,+m);
        if(m%10==0){
        lblCover.setLocation(-m,+5);
        }else{
        lblCover.setLocation(+m,+5);    
        }
        if(m==100){
            lblCover.setLocation(p); 
            lblEmFalling2.setLocation(u); 
            lblEmFalling.setLocation(g); 
        }
        if(m==220){
            
            JpaneEmFalling.setVisible(false);
            jLayeredPane2.setVisible(false);
            JpaneGoblin.setVisible(true);
            jPaneUndead.setVisible(true);
            JpaneChamStart.setVisible(true);
            JpaneChamIdle.setVisible(false); 
            Update();
            rtimer.stop();
            
        }
        }
        });
    rtimer.start();

    }
    
    public void descendFloor() {
           if (currentFloor >= 1) {
                currentFloor--;
                txtDia.append("\n- - - You descended to floor " + currentFloor+" - - -");
                points = (monsterCount*currentFloor)+playerHP;
                resetOpponents();
            } else {
                jPaneUndead.setVisible(false);
                JpaneGoblin.setVisible(false);
                YouWin.setVisible(true);
                JpaneChamIdle.setVisible(false);
                lblBoss.setVisible(false);
                JOptionPane.showMessageDialog(null,"You have escaped","CONGRATULATIONS", JOptionPane.INFORMATION_MESSAGE);
                reset();
            }
        }

    
    @Override
    public void playerAttack() {
    btnBasicAttack.setEnabled(false);
    monsterDamage1 = random.nextInt(30) +1000+playerLevel * levelDamageMultiplier;
    monsterDamage2 = random.nextInt(30) + 5000+playerLevel * levelDamageMultiplier;
    
    m=5;
    txtDia.append("\nPlayer used Basic skill....\n");
//    textNarrate(narrate);   
//    narrate="";
     
    if (monsterHP1 > 0) {
        monsterHP1 = (monsterHP1 > monsterDamage1) ? monsterHP1 - monsterDamage1 : 0;
        txtDia.append("\n"+getHeroType() + " dealt " + monsterDamage1 + " damage to " + getMonsterName1() + ".\n");

        if (monsterHP1 <= 0 && !defeatedMonster1) {
            txtDia.append("\n" + getMonsterName1() + " is defeated!\n");
            defeatedMonster1 = true;
            monsterCount++;
            experiencePoints += 20;
            txtDia.append("Gained 20 experience!\n");

        }
    }

    if (monsterHP2 > 0) {
        monsterHP2 = (monsterHP2 > monsterDamage2) ? monsterHP2 - monsterDamage2 : 0;
        txtDia.append(narrate = getHeroType() + " dealt " + monsterDamage2 + " damage to " + getMonsterName2() + ".");
        if (monsterHP2 <= 0 && !defeatedMonster2) {
            txtDia.append("\n" + getMonsterName2() + " is defeated!");
           defeatedMonster1 = true;
            monsterCount++;
            experiencePoints += 25;
            txtDia.append("Gained 25 experience!\n");
            
        }
    }
 
     if (experiencePoints >= experienceThreshold) {
                levelUp();
        }
     
       timer = new Timer(5, new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent e) {
        
        m = m + 1;
        lblRunning.setLocation(+m,+5);
        
        if(m==255){ //character reach the enemy location
        
        JpaneStrike.setVisible(true); // show attack motion of character
        jLayeredPane1.setVisible(false); //hide running animation
        }
        
        if(m==280){
         JpaneAttack.setVisible(true); //show attack effects on enemy
        }
        
        if(m==300){
        JpaneAttack.setVisible(false);
        JpaneAttack2.setVisible(true);
        if(defeatedMonster2&&mark==0){
            jPaneEmDead22.setVisible(true);
        }
        if(defeatedMonster1&&mak==0){
            jPaneEmDead1.setVisible(true);
        }
        }
        
        if(m==330){
        JpaneAttack2.setVisible(false); //hide attack effects on enemy
        if(defeatedMonster2&&mark==0){
            jPaneEmDead22.setVisible(false);
            jPaneEmDead222.setVisible(true);
        }
        if(defeatedMonster1&&mak==0){
            jPaneEmDead1.setVisible(false);
            jPaneEmDead2.setVisible(true);
        }
        }
        
        if(m==335){
        JpaneStrike.setVisible(false);// hide attack motion of character
        JpaneChamIdle.setVisible(true);
        btnBasicAttack.setEnabled(true);
        if (areOpponentsAlive() == 1) {
            if(defeatedMonster2&&mark==0){
            jPaneEmDead222.setVisible(false);
            jPaneUndead.setVisible(false);
            mark =1;
            }
            if(defeatedMonster1&&mak==0){
            jPaneEmDead2.setVisible(false);
            JpaneGoblin.setVisible(false);
            mak =1;
            }
                opponentsAttack();
                timer.stop();
            }
        
        if (areOpponentsAlive() == 0) {
            jPaneEmDead2.setVisible(false);
            jPaneEmDead222.setVisible(false);
                descendFloor();
                
                timer.stop();
            }
        
        timer.stop();
        }
        }
        });
    timer.start();
    
    
    
    
   
}
    

    @Override
    public void opponentsAttack() {
        JpaneChamIdle.setVisible(false);
        JpaneChamStart.setVisible(false);
        btnBasicAttack.setEnabled(false);
        m = 5;
        n=5;
            if (monsterHP1 > 0 && monsterHP2 > 0) {
                txtDia.append("\n"+getMonsterName1()+" and "+getMonsterName2()+" attack "+getHeroType()+"!\n");
            } else if (monsterHP1 > 0) {
                txtDia.append("\n"+getMonsterName1()+ " attacks "+getHeroType()+"!");
            } else if (monsterHP2 > 0) {
                txtDia.append("\n"+getMonsterName2()+" attacks "+getHeroType()+"!");
            }

            if (monsterHP1 > 0) {
                int monsterDamage1 = random.nextInt( 31) +10+ floorDamage;
                playerHP -= monsterDamage1;
                txtDia.append(getMonsterName1()+" dealt " + monsterDamage1 + " damage to "+getHeroType()+".\n");
            }

            if (monsterHP2 > 0) {
                int monsterDamage2 = random.nextInt(  31) +10+ floorDamage;
                playerHP -= monsterDamage2;
                txtDia.append(getMonsterName2()+" dealt " + monsterDamage2 + " damage to "+getHeroType()+".\n");
            }
            
    Optimer = new Timer(5, new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent e) {
        
        m = m + 1;
        n=n+1;
        if (isPlayerAlive() == 0) {                      // if player is dead
         
            JLayeredDeadPaladin.setVisible(true); // character dead animation
            if(m==20){
            jPaneEmAttack.setVisible(true);       //
            }
            if(m==70){
            jPaneEmAttack.setVisible(false);
            }   
            if(m==110){
             JLayeredDeadPaladin.setVisible(true);
            }
            
            if(m==150){
            JLayeredDeadPaladin.setVisible(false);
            
            reset();
           

            Optimer.stop();
            }
        } else {                                        // if player is alive
            JpaneDef.setVisible(true);                  // character defense animation
            if(m==100){
            jPaneEmAttack.setVisible(true);             // enemy attack animation
            
            }
            
            if(m==140){
            jPaneEmAttack.setVisible(false);
            JpaneDef.setVisible(false);
            JpaneChamStart.setVisible(true);            // backing up cham to start position
            Update();
            btnBasicAttack.setEnabled(true);
            Optimer.stop();
            } 
            
        }
    }
    });
    
    Optimer.start();
    }
    
    public void useSkill() {
            if (turnsSinceLastSkill >= skillCooldown) {
                System.out.println("Paladin used HOLY SMITE!");
                skillDamage = random.nextInt(30) + 30;
                opponentsTakeDamage(skillDamage);
                turnsSinceLastSkill = 0;  // Reset the cooldown
            }else {
                System.out.println("HOLY SMITE is on cooldown. Choose another option.");
            }
        }
    
    public void opponentsTakeDamage(int damage) {
            if (monsterHP1 > 0) {
                monsterHP1 = (monsterHP1 > damage) ? monsterHP1 - damage : 0;
                System.out.println(getHeroType()+" dealt " + damage + " damage to "+getMonsterName1());
                if (monsterHP1 <= 0) {
                    System.out.println(getMonsterName1()+" is defeated!");
                    monsterCount++;
                    experiencePoints += 20;
                    System.out.println("Gained 20 experience\n");
                }
            }

            if (monsterHP2 > 0) {
                monsterHP2 = (monsterHP2 > damage) ? monsterHP2 - damage : 0;
                System.out.println(getHeroType()+" dealt " + damage + " damage to "+getMonsterName2());
                if (monsterHP2 <= 0) {
                    System.out.println(getMonsterName2()+" is defeated!");
                    monsterCount++;
                    experiencePoints += 25;
                    System.out.println("Gained 25 experience!\n");
                }
            }
        }


    private boolean isBossAlive() {
            return bossHP > 0;
        }
     
        @Override
        public int isPlayerAlive() {
            return playerHP > 0 ? 1 : 0;
        }

        @Override
        public int areOpponentsAlive() {
            return (monsterHP1 > 0 || monsterHP2 > 0) ? 1 : 0;
        }

        @Override
        public int getPlayerHP() {
            return playerHP;
        }

        @Override
        public int getMonsterHP1() {
            return monsterHP1;
        }

        @Override
        public int getMonsterHP2() {
            return monsterHP2;
        }

        @Override
        public String getHeroType() {
            return "Paladin";
        }
        
        @Override
        public String getMonsterName1(){
            return "Goblin";
        }
        
        @Override
        public String getMonsterName2(){
            return "Undead";
        }
        


    @Override
    public void playGame() {
      Scanner scan = new Scanner(System.in);

            do {
            System.out.println("\n" + getHeroType() + "'s HP: " + getPlayerHP() +
                " |"+getMonsterName1()+ ": " + df.format(getMonsterHP1()) +
                " |"+getMonsterName2()+ ": " + df.format(getMonsterHP2()) +
                " | Floor: " + currentFloor);

            System.out.print("Pleas Select Attack: ");
            int choice = scan.nextInt();
            System.out.println("");

            if (choice == 1) {
            playerAttack();
            if (areOpponentsAlive() == 1) {
                opponentsAttack();
            }
        }
            else if(choice == 2){
                useSkill();
                if (areOpponentsAlive() == 1) {
                    opponentsAttack();
                }
            }
             turnsSinceLastSkill++;
             if (experiencePoints >= experienceThreshold) {
                levelUp();
        }
             
            if (areOpponentsAlive() == 0) {
                if(currentFloor != 1){
                floorHPMultiplier += 0.1;
                resetOpponents();
                descendFloor();
            }
        } 
        // Check for level 


        
        
            if(currentFloor > 17 && currentFloor < 10){ //floor 17 to 10
                floorDamage = 10; //damage modifier for the enemies
        }
            
             
            if(currentFloor > 10 && currentFloor < 1){ //floor 10 to 1
                floorDamage = 20;
        }
            
           if(currentFloor == 17){
                //Boss Stats
                bossName = "Dark Sorcerer Malgrim";
                bossSkill = "Shadow Bolt Barrage";
                bossHP = 200;
                bossArmor = random.nextDouble(31) * floorHPMultiplier;
                bossHP += bossArmor;
                bossDamage = random.nextInt(60) + playerLevel * 5;
                bossCounterAttackDamage = random.nextInt(51) + floorDamage;
                bossBattle();
            }
            
            if(currentFloor == 10){
                bossName = "Fire Elemental Pyronix";
                bossSkill = "Inferno Burst";
                bossHP = 400;
                bossArmor = random.nextDouble(50) + 40 * floorHPMultiplier;
                bossHP += bossArmor;
                bossDamage = random.nextInt(60) + playerLevel * 10;
                bossCounterAttackDamage = random.nextInt(51) + floorDamage;
                bossBattle();
            }
            
            if(currentFloor == 1){
                bossName = "Ice Dragon Glacius";
                bossSkill = "Frost Nova";
                bossHP = 600;
                bossArmor = random.nextDouble(60) + 50 * floorHPMultiplier;
                bossHP += bossArmor;
                bossDamage = random.nextInt(60) + playerLevel * 15;
                bossCounterAttackDamage = random.nextInt(51) + floorDamage;
                bossBattle();
            }

    } while (currentFloor >= 1 && isPlayerAlive() == 1 && areOpponentsAlive() == 1);

            if (currentFloor == 0) {
                System.out.println("\nYou Escaped the Dungeon!");
            System.out.print("Enter name for leaderboard: ");
            scan.nextLine();
            String name = scan.nextLine();
            String url = "jdbc:mysql://localhost:3306/leaderboard";
            String username = "root";
            String password = "";
            String insertQuery = "INSERT INTO leaderboard (name ,stage) VALUES (?,?)";
            String selectQuery = "SELECT stage FROM leaderboard";
            try {
            // Load and register the JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Establish a connection
            Connection connection = DriverManager.getConnection(url, username, password);
            
            // Create a PreparedStatement for insert
            PreparedStatement insertStatement = connection.prepareStatement(insertQuery);
            
            // Set the name parameter for insert
            insertStatement.setString(1, name);
            insertStatement.setInt(2, currentFloor);
            
            // Execute the insert query
            int rowsAffected = insertStatement.executeUpdate();
            
            // Close the insert statement
            insertStatement.close();
            
            // Create a Statement for select
            Statement selectStatement = connection.createStatement();
            
            // Execute the select query
            ResultSet resultSet = selectStatement.executeQuery(selectQuery);
            
            
            // Close resources
            resultSet.close();
            selectStatement.close();
            connection.close();
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
//                calculateAndDisplayScore();
        }   else {
            System.out.println("\nGame Over! "+getHeroType()+" has been defeated.");
            System.out.print("Enter name for leaderboard: ");
            scan.nextLine();
            String name = scan.nextLine();
            String url = "jdbc:mysql://localhost:3306/leaderboard";
            String username = "root";
            String password = "";
            String insertQuery = "INSERT INTO leaderboard (name ,stage) VALUES (?,?)";
            String selectQuery = "SELECT stage FROM leaderboard";
            try {
            // Load and register the JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Establish a connection
            Connection connection = DriverManager.getConnection(url, username, password);
            
            // Create a PreparedStatement for insert
            PreparedStatement insertStatement = connection.prepareStatement(insertQuery);
            
            // Set the name parameter for insert
            insertStatement.setString(1, name);
            insertStatement.setInt(2, currentFloor);
            
            // Execute the insert query
            int rowsAffected = insertStatement.executeUpdate();
            
            // Close the insert statement
            insertStatement.close();
            
            // Create a Statement for select
            Statement selectStatement = connection.createStatement();
            
            // Execute the select query
            ResultSet resultSet = selectStatement.executeQuery(selectQuery);
            
            
            // Close resources
            resultSet.close();
            selectStatement.close();
            connection.close();
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }}

    }
      
       public void bossBattle() {
    System.out.println("\n[ Boss Battle - Floor " + currentFloor + " ]");
    System.out.println("Boss: " + bossName);
    System.out.println("Boss HP: " + df.format(bossHP));

    Scanner scan = new Scanner(System.in);

    do {
        printPlayerStats();

        System.out.print("Press 1 to Attack || Press 2 to use skill: ");
        int choice = scan.nextInt();

        if (choice == 1) {
            playerAttackBoss();
            if (isBossAlive()) {
                bossCounterAttack();
            }
        } else if (choice == 2) {
            useSkill();
            if (isBossAlive()) {
                bossCounterAttack();
            }
        }
        turnsSinceLastSkill++;

        if (!isBossAlive()) {
            System.out.println("\n" + bossName + " is defeated!");
            break;
        }

        // Boss attacks
        bossAttack();
    } while (isPlayerAlive() == 1 && isBossAlive());

    currentFloor--;
}

public void playerAttackBoss() {
    int damageDealt = random.nextInt(60) + 50; // playerLevel * 10;
    bossHP = (bossHP > damageDealt) ? bossHP - damageDealt : 0;
    System.out.println("\n" + getHeroType() + " dealt " + damageDealt + " damage to " + bossName + ".");
}

public void bossAttack() {
    if (isPlayerAlive() == 1) {
        playerHP -= bossCounterAttackDamage;
        System.out.println("\n" + bossName + " used "+bossSkill+" to attack! " + getHeroType() + " takes " + bossCounterAttackDamage + " damage.");
    }
}

public void bossCounterAttack() {
    System.out.println("\n" + bossName + " counterattacks!");
    int damage = random.nextInt(51) + floorDamage;
    playerHP -= damage;
    System.out.println("\n" + getHeroType() + " takes " + damage + " damage.");
}

    
    private void printPlayerStats() {
            System.out.println("\n"+getHeroType()+"'s HP: " + df.format(playerHP) +
                " | Boss HP: " + df.format(bossHP) +
                " | Floor: " + currentFloor);
    }   

}
