
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kiara
 */
public class HardPaladin1 extends javax.swing.JFrame implements TOMInterface{

        int txt=0,m=5;
       private int playerHP;
        private int armor;
        private int goblinHP = 50;
        private int undeadHP = 70;
        private double goblinArmor;
        private double undeadArmor;
        private int goblinDamage;
        private int undeadDamage;
        private int currentFloor = 17;
        private int experiencePoints = 0;
        private int experienceThreshold = 35; 
        private int playerLevel = 1;
        private double floorHPMultiplier = 0.3;
        private int floorDamage = 0;


        private Random random = new Random();
    /**
     * Creates new form StartGame
     */
    public HardPaladin1() {
        initComponents();
        jLayeredPane1.setVisible(false);
        JpaneChamIdle.setVisible(false);
        JpaneAttack.setVisible(false);
        JpaneAttack2.setVisible(false);
        JpaneStrike.setVisible(false);
        JLayeredDeadPaladin.setVisible(false);
        jPaneEmAttack.setVisible(false);
        this.setBackground(Color.decode("#3D748F"));
        initIntro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpaneBack = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        JpaneGoblin = new javax.swing.JLayeredPane();
        lblGoblin = new javax.swing.JLabel();
        JpaneAttack = new javax.swing.JLayeredPane();
        lblAttack = new javax.swing.JLabel();
        JpaneAttack2 = new javax.swing.JLayeredPane();
        lblAttack2 = new javax.swing.JLabel();
        JpaneBoosIdle = new javax.swing.JLayeredPane();
        lblBoss = new javax.swing.JLabel();
        JpaneChamStart = new javax.swing.JLayeredPane();
        ldlChamStart = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblRunning = new javax.swing.JLabel();
        JLayeredDeadPaladin = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jPaneEmAttack = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        JpaneChamIdle = new javax.swing.JLayeredPane();
        lblIdle = new javax.swing.JLabel();
        JpaneStrike = new javax.swing.JLayeredPane();
        lblStrike = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDia = new javax.swing.JTextArea();
        btnAttack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(61, 116, 143));
        setForeground(new java.awt.Color(61, 116, 143));
        setResizable(false);

        JpaneBack.setMaximumSize(new java.awt.Dimension(960, 672));
        JpaneBack.setMinimumSize(new java.awt.Dimension(960, 672));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/fb2ab0e7-4d0a-4fea-b77c-34aa0f6a194b.gif"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblGoblin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Goblins.gif"))); // NOI18N

        JpaneGoblin.setLayer(lblGoblin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JpaneGoblinLayout = new javax.swing.GroupLayout(JpaneGoblin);
        JpaneGoblin.setLayout(JpaneGoblinLayout);
        JpaneGoblinLayout.setHorizontalGroup(
            JpaneGoblinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneGoblinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGoblin, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpaneGoblinLayout.setVerticalGroup(
            JpaneGoblinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneGoblinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGoblin, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        lblAttack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Slash 2_1.gif"))); // NOI18N
        lblAttack.setToolTipText("");

        JpaneAttack.setLayer(lblAttack, javax.swing.JLayeredPane.MODAL_LAYER);

        javax.swing.GroupLayout JpaneAttackLayout = new javax.swing.GroupLayout(JpaneAttack);
        JpaneAttack.setLayout(JpaneAttackLayout);
        JpaneAttackLayout.setHorizontalGroup(
            JpaneAttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneAttackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        JpaneAttackLayout.setVerticalGroup(
            JpaneAttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneAttackLayout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(lblAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblAttack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Slash 3.gif"))); // NOI18N

        JpaneAttack2.setLayer(lblAttack2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JpaneAttack2Layout = new javax.swing.GroupLayout(JpaneAttack2);
        JpaneAttack2.setLayout(JpaneAttack2Layout);
        JpaneAttack2Layout.setHorizontalGroup(
            JpaneAttack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneAttack2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAttack2)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        JpaneAttack2Layout.setVerticalGroup(
            JpaneAttack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneAttack2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblAttack2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        lblBoss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/output-onlinegiftools (2).gif"))); // NOI18N

        JpaneBoosIdle.setLayer(lblBoss, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JpaneBoosIdleLayout = new javax.swing.GroupLayout(JpaneBoosIdle);
        JpaneBoosIdle.setLayout(JpaneBoosIdleLayout);
        JpaneBoosIdleLayout.setHorizontalGroup(
            JpaneBoosIdleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneBoosIdleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBoss, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JpaneBoosIdleLayout.setVerticalGroup(
            JpaneBoosIdleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneBoosIdleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBoss, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ldlChamStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Paladin IDLE_1.gif"))); // NOI18N

        JpaneChamStart.setLayer(ldlChamStart, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JpaneChamStartLayout = new javax.swing.GroupLayout(JpaneChamStart);
        JpaneChamStart.setLayout(JpaneChamStartLayout);
        JpaneChamStartLayout.setHorizontalGroup(
            JpaneChamStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneChamStartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ldlChamStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpaneChamStartLayout.setVerticalGroup(
            JpaneChamStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ldlChamStart)
        );

        lblRunning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Paladin RUN_1.gif"))); // NOI18N
        lblRunning.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblRunningPropertyChange(evt);
            }
        });

        jLayeredPane1.setLayer(lblRunning, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunning, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRunning, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/paladindead (1).gif"))); // NOI18N
        jLabel1.setText("jLabel1");

        JLayeredDeadPaladin.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JLayeredDeadPaladinLayout = new javax.swing.GroupLayout(JLayeredDeadPaladin);
        JLayeredDeadPaladin.setLayout(JLayeredDeadPaladinLayout);
        JLayeredDeadPaladinLayout.setHorizontalGroup(
            JLayeredDeadPaladinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JLayeredDeadPaladinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JLayeredDeadPaladinLayout.setVerticalGroup(
            JLayeredDeadPaladinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLayeredDeadPaladinLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Slash 1.gif"))); // NOI18N

        jPaneEmAttack.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPaneEmAttackLayout = new javax.swing.GroupLayout(jPaneEmAttack);
        jPaneEmAttack.setLayout(jPaneEmAttackLayout);
        jPaneEmAttackLayout.setHorizontalGroup(
            jPaneEmAttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneEmAttackLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPaneEmAttackLayout.setVerticalGroup(
            jPaneEmAttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneEmAttackLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        lblIdle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Paladin IDLE_1.gif"))); // NOI18N

        JpaneChamIdle.setLayer(lblIdle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JpaneChamIdleLayout = new javax.swing.GroupLayout(JpaneChamIdle);
        JpaneChamIdle.setLayout(JpaneChamIdleLayout);
        JpaneChamIdleLayout.setHorizontalGroup(
            JpaneChamIdleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIdle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JpaneChamIdleLayout.setVerticalGroup(
            JpaneChamIdleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneChamIdleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIdle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        lblStrike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Paladin attack.gif"))); // NOI18N

        JpaneStrike.setLayer(lblStrike, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JpaneStrikeLayout = new javax.swing.GroupLayout(JpaneStrike);
        JpaneStrike.setLayout(JpaneStrikeLayout);
        JpaneStrikeLayout.setHorizontalGroup(
            JpaneStrikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneStrikeLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lblStrike, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JpaneStrikeLayout.setVerticalGroup(
            JpaneStrikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpaneStrikeLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(lblStrike, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JpaneBack.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JpaneBack.setLayer(JpaneGoblin, javax.swing.JLayeredPane.PALETTE_LAYER);
        JpaneBack.setLayer(JpaneAttack, javax.swing.JLayeredPane.POPUP_LAYER);
        JpaneBack.setLayer(JpaneAttack2, javax.swing.JLayeredPane.MODAL_LAYER);
        JpaneBack.setLayer(JpaneBoosIdle, javax.swing.JLayeredPane.PALETTE_LAYER);
        JpaneBack.setLayer(JpaneChamStart, javax.swing.JLayeredPane.MODAL_LAYER);
        JpaneBack.setLayer(jLayeredPane1, javax.swing.JLayeredPane.PALETTE_LAYER);
        JpaneBack.setLayer(JLayeredDeadPaladin, javax.swing.JLayeredPane.MODAL_LAYER);
        JpaneBack.setLayer(jPaneEmAttack, javax.swing.JLayeredPane.POPUP_LAYER);
        JpaneBack.setLayer(JpaneChamIdle, javax.swing.JLayeredPane.MODAL_LAYER);
        JpaneBack.setLayer(JpaneStrike, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout JpaneBackLayout = new javax.swing.GroupLayout(JpaneBack);
        JpaneBack.setLayout(JpaneBackLayout);
        JpaneBackLayout.setHorizontalGroup(
            JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneBackLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(257, 257, 257)
                    .addComponent(JpaneChamIdle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(593, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(621, 621, 621)
                    .addComponent(JpaneBoosIdle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(609, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(339, 339, 339)
                    .addComponent(JpaneGoblin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(482, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(335, 335, 335)
                    .addComponent(JpaneAttack)
                    .addGap(426, 426, 426)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(254, 254, 254)
                    .addComponent(JpaneStrike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(595, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(299, 299, 299)
                    .addComponent(JpaneAttack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(419, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JpaneChamStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(792, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(259, 259, 259)
                    .addComponent(JLayeredDeadPaladin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(575, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(250, 250, 250)
                    .addComponent(jPaneEmAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(430, Short.MAX_VALUE)))
        );
        JpaneBackLayout.setVerticalGroup(
            JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneBackLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(JpaneChamIdle, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(318, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(JpaneBoosIdle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(216, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(224, 224, 224)
                    .addComponent(JpaneGoblin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(316, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(JpaneAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(330, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(JpaneStrike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(325, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(JpaneAttack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(309, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(230, 230, 230)
                    .addComponent(JpaneChamStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(193, 193, 193)
                    .addComponent(JLayeredDeadPaladin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
            .addGroup(JpaneBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpaneBackLayout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jPaneEmAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(229, Short.MAX_VALUE)))
        );

        txtDia.setBackground(new java.awt.Color(57, 114, 196));
        txtDia.setColumns(20);
        txtDia.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtDia.setLineWrap(true);
        txtDia.setRows(5);
        txtDia.setWrapStyleWord(true);
        txtDia.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(61, 116, 143)));
        txtDia.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDia.setMargin(new java.awt.Insets(0, 6, 2, 6));
        jScrollPane1.setViewportView(txtDia);

        btnAttack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Paladin attack.gif"))); // NOI18N
        btnAttack.setText("Attack");
        btnAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpaneBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpaneBack, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRunningPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblRunningPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRunningPropertyChange

    private void btnAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttackActionPerformed
       jLayeredPane1.setVisible(true);
    JpaneChamStart.setVisible(false);
    initAttack();  // Initializes the attack animations, etc.

    playerAttack();  // Perform player's attack immediately
    if (areOpponentsAlive() == 1) {
        opponentsAttack();  // Perform opponents' attack if they are still alive
    }
    if (areOpponentsAlive() == 0) {
        txtDia.append("All opponents defeated!\n");
    }
    if (isPlayerAlive() == 0) {
        txtDia.append("Game Over! Player defeated!\n");
        
    }
    }//GEN-LAST:event_btnAttackActionPerformed
private void initPlayerAttack() {
    Timer attackTimer = new Timer(1000, new ActionListener() {
        private int count = 0;

        @Override
        public void actionPerformed(ActionEvent e) {
            switch (count) {
                case 0:
                    playerAttack();
                    if (areOpponentsAlive() == 0) {
                        ((Timer) e.getSource()).stop(); // Stop the timer if no opponents are alive
                    }
                    break;
                case 1:
                    opponentsAttack();
                    if (isPlayerAlive() == 0) {
                        System.out.println("\nGame Over!");
                        ((Timer) e.getSource()).stop(); // Stop the timer if player is dead
                    }
                    break;
                default:
                    ((Timer) e.getSource()).stop(); // Stop the timer after all actions are processed
                    break;
            }
            count++;
        }
    });
    attackTimer.setInitialDelay(0); // Start immediately
    attackTimer.start();
}
    private void initAttack(){
        Point p = new Point(lblRunning.getLocation());
        
        Timer timer = new Timer(5, new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent e) {
//        p.move(+0,+10);
        m = m + 1;
        lblRunning.setLocation(+m,+5);
        if(m==255){
        JpaneStrike.setVisible(true);
        jLayeredPane1.setVisible(false);
        }
        if(m==280){
         JpaneAttack.setVisible(true);
        }
        if(m==300){
        JpaneAttack.setVisible(false);
        JpaneAttack2.setVisible(true);
        }
        if(m==330){
        JpaneAttack2.setVisible(false);
        }
        if(m==335){
        JpaneStrike.setVisible(false);
//        JpaneChamIdle.setVisible(true);
        JLayeredDeadPaladin.setVisible(true);
        }
        
        if(m==390){
        jPaneEmAttack.setVisible(true);
        }
        if(m==420){
        jPaneEmAttack.setVisible(false);
        }
        
        
        if(m==450){
        JLayeredDeadPaladin.setVisible(false);
        }
        }
        });
    timer.setDelay(10);

    timer.start();
        
    }
    
    private void initIntro(){
       playerHP = 70;
       armor = random.nextInt(25);
       goblinArmor = random.nextInt(21);
       undeadArmor = random.nextInt(11);

        
        
        Timer time = new Timer(500, new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent e) {
        String intro;
        
        intro = "Paladin's Armor Activated. Paladin gained " + armor + " Additional HP. ";

        txtDia.setText(txtDia.getText() + String.valueOf(intro.charAt(txt)));
        txt = txt + 1;
        
//        if(isEmpty(intro.charAt(txt))){
//            txtDia.setText("Gargoyle's Armor Activated. Gargoyle gained " + gargoyleArmor + " Additional HP.");
//        }
//        if(txt == 100){
//            txtDia.setText("Gargoyle's Armor Activated. Gargoyle gained " + gargoyleArmor + " Additional HP.");
//        } else if(txt == 150){
//            txtDia.setText("the Unyielding: Archon Valthorn's Armor Activated. Archon Valthorn gained " + gargoyleArmor + " Additional HP.");
//        }
         
        }
        });
        time.setDelay(40);
        time.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyFl1Paladin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyFl1Paladin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyFl1Paladin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyFl1Paladin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyFl1Paladin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane JLayeredDeadPaladin;
    private javax.swing.JLayeredPane JpaneAttack;
    private javax.swing.JLayeredPane JpaneAttack2;
    private javax.swing.JLayeredPane JpaneBack;
    private javax.swing.JLayeredPane JpaneBoosIdle;
    private javax.swing.JLayeredPane JpaneChamIdle;
    private javax.swing.JLayeredPane JpaneChamStart;
    private javax.swing.JLayeredPane JpaneGoblin;
    private javax.swing.JLayeredPane JpaneStrike;
    private javax.swing.JButton btnAttack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jPaneEmAttack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAttack;
    private javax.swing.JLabel lblAttack2;
    private javax.swing.JLabel lblBoss;
    private javax.swing.JLabel lblGoblin;
    private javax.swing.JLabel lblIdle;
    private javax.swing.JLabel lblRunning;
    private javax.swing.JLabel lblStrike;
    private javax.swing.JLabel ldlChamStart;
    private javax.swing.JTextArea txtDia;
    // End of variables declaration//GEN-END:variables
    public void levelUp() {
  
            experienceThreshold += 20;
            playerHP += 30;
            playerLevel++;

            System.out.println("Congratulations! You leveled up to level " + playerLevel +
            ". Stats are increased!");

            // Reset experiencePoints
            experiencePoints = 0;
        }
    
    public void resetOpponents() {
            goblinHP = 50;
            undeadHP = 70;

            goblinArmor = random.nextDouble(21) * floorHPMultiplier;
            undeadArmor = random.nextDouble(11) * floorHPMultiplier;

            System.out.println("Goblin's Armor Activated. Goblin gained " + (int)goblinArmor + " Additional HP.");
            System.out.println("Undead's Armor Activated. Undead gained " + (int)undeadArmor + " Additional HP.");

            goblinHP += goblinArmor;
            undeadHP += undeadArmor;
    }
    
    public void descendFloor() {
            if (currentFloor >= 1) {
                currentFloor--;
                System.out.println("You descended to floor " + currentFloor);
            } else {
                System.out.println("You are on the lowest floor. No more descending.");
            }
        }

    
    @Override
    public void playerAttack() {
    
            goblinDamage = random.nextInt(50) + playerLevel * 7;
            undeadDamage = random.nextInt(50) + playerLevel * 7;

            if (goblinHP > 0) {
                goblinHP = (goblinHP > goblinDamage) ? goblinHP - goblinDamage : 0;
                System.out.println("Mage dealt " + goblinDamage + " damage to Goblin.");
                if (goblinHP == 0) {
                    System.out.println("Goblin is defeated!");
                    experiencePoints += 25;
                    System.out.println("Gained 25 experience");
                }
            }

            if (undeadHP > 0) {
                undeadHP = (undeadHP > undeadDamage) ? undeadHP - undeadDamage : 0;
                System.out.println("Mage dealt " + undeadDamage + " damage to Undead.");
                if (undeadHP == 0) {
                    System.out.println("Undead is defeated!");
                    experiencePoints += 30;
                    System.out.println("Gained 30 experience!");
                }
            }

}
    

    @Override
    public void opponentsAttack() {
        StringBuilder attackMessages = new StringBuilder();
    if (goblinHP > 0 && undeadHP > 0) {
                System.out.println("\nGoblin and Undead attack Mage!");
            } else if (goblinHP > 0) {
                System.out.println("\nGoblin attacks Mage!");
            } else if (undeadHP > 0) {
                attackMessages.append("\nUndead attacks Mage!");
            }

            if (goblinHP > 0) {
                int goblinDamage = random.nextInt( 31) + floorDamage;
                playerHP -= goblinDamage;
                System.out.println("Goblin dealt " + goblinDamage + " damage to Mage.");
            }

            if (undeadHP > 0) {
                int undeadDamage = random.nextInt(  51) + floorDamage;
                playerHP -= undeadDamage;
                System.out.println("Undead dealt " + undeadDamage + " damage to Mage.");
            }

    txtDia.append(attackMessages.toString());  // Appends the complete set of attack details at once
    }

    @Override
    public int isPlayerAlive() {
        return playerHP > 0 ? 1 : 0;
    }

    @Override
    public int areOpponentsAlive() {
        return (gargoyleHP > 0 || lancerHP > 0) ? 1 : 0;
    }

    @Override
    public int getPlayerHP() {
      return playerHP;
    }

    @Override
    public int getGargoyleHP() {
        return gargoyleHP;
    }

    @Override
    public int getLancerHP() {
       return lancerHP;
    }

    @Override
    public void playGame() {
     Scanner scan = new Scanner(System.in);

            do {
            System.out.println("\n" + getHeroType() + "'s HP: " + getPlayerHP() +
                " | Gargoyle HP: " + (int)getGargoyleHP() +
                " | Lancer HP: " + (int)getLancerHP() +
                " | Floor: " + currentFloor);

            System.out.print("Press 1 to Attack: ");
            int choice = scan.nextInt();

            if (choice == 1) {
            playerAttack();
            if (areOpponentsAlive() == 1) {
                opponentsAttack();
            }
        } 
          
            if (areOpponentsAlive() == 0) {
                if(currentFloor != 1){
                floorHPMultiplier += 0.1;
                resetOpponents();
                descendFloor();
                }
        } 
        // Check for level 
            if (experiencePoints >= experienceThreshold) {
                levelUp();
        }
        
            if(currentFloor >= 17 && currentFloor <= 10){ //floor 17 to 10
                floorDamage = 10; //damage modifier for the enemies
        }
        
            if(currentFloor >= 10 && currentFloor <= 1){ //floor 10 to 1
                floorDamage = 20;
        }

    } while (currentFloor >= 1 && isPlayerAlive() == 1 && areOpponentsAlive() == 1);

            if (currentFloor == 1) {
                System.out.println("You Escaped the Dungeon!");
        }   else {
            System.out.println("\nGame Over!");
    }
    }

    @Override
    public String getHeroType() {
        return "Paladin";
    }

    @Override
    public int getMonsterHP1() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public int getMonsterHP2() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public String getMonsterName1() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public String getMonsterName2() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
